'use client';
import Link from 'next/link';
import {useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {saveLesson,changeLessonStatus} from '@/app/lessons/actions';
import {localStamp,moveDay,validDay} from '@/lib/lesson-time';
import type {Choice,ArenaChoice,LessonView,LessonError,LessonResult} from '@/lib/lesson-types';
const words={
he:{title:'יומן שיעורי רכיבה',back:'לוח הניהול',add:'שיעור חדש',edit:'עריכת שיעור',date:'תאריך',time:'שעת התחלה',instructor:'מדריך',arena:'מגרש',rider:'רוכב',horse:'סוס',participants:'משתתפים',addParticipant:'הוספת משתתף',remove:'הסרה',choose:'בחרו…',notes:'הערות',saveButton:'שמירת השיעור',saving:'שומר…',close:'סגירה',cancelLesson:'ביטול שיעור',complete:'סימון כהושלם',SCHEDULED:'מתוכנן',COMPLETED:'הושלם',CANCELLED:'בוטל',today:'היום',previous:'יום קודם',next:'יום הבא',refresh:'רענון',empty:'אין שיעורים להצגה ביום שנבחר.',duration:'כל שיעור נמשך 30 דקות. ניתן להוסיף כמה משתתפים לאותו שיעור.',timezone:'אזור זמן',success:'השיעור נשמר בהצלחה.',changed:'מצב השיעור עודכן.',invalid:'בדוק את השדות. יש לבחור לפחות משתתף אחד, ללא חזרה על אותו רוכב או סוס.',timeError:'השעה אינה תקינה או מופיעה פעמיים במעבר שעון. בחר שעה אחרת.',farm:'נדרשת חווה אחת מוגדרת במערכת.',save:'לא הצלחנו לטעון או לשמור נתונים. רענן ובדוק את החיבור.',disabled:'הפעולה זמינה במצב פיתוח בלבד.',inactive:'אחת הבחירות אינה פעילה או אינה שייכת לחווה. רענן ובחר נתונים פעילים.',conflict:'קיימת חפיפה עם שיעור אחר עבור המגרש, המדריך, אחד הרוכבים או אחד הסוסים. שנה את השעה או השיבוץ.',stale:'השיעור השתנה מאז פתיחת הטופס. סגור את הטופס, רענן ופתח אותו מחדש.',future:'אפשר לסמן שיעור כהושלם רק לאחר שעת הסיום שלו.',missing:'דרושים לפחות מדריך, רוכב, סוס ומגרש פעילים לשיבוץ שיעור.',instructors:'ניהול מדריכים',riders:'ניהול רוכבים',horses:'ניהול סוסים',inactiveLabel:'לא פעיל',confirmCancel:'לבטל את השיעור? הוא יישמר בהיסטוריה והזמן יתפנה.',confirmComplete:'לסמן את השיעור כהושלם?',all:'כל המצבים',group:'קבוצתי',private:'פרטי',max:'עד 50 משתתפים בשיעור.',history:'היסטוריית שינויים',historyEmpty:'אין עדיין שינויים מתועדים.',by:'על ידי',system:'מערכת',CREATED_AUDIT:'נוצר',UPDATED_AUDIT:'עודכן',CANCELLED_AUDIT:'בוטל',COMPLETED_AUDIT:'הושלם'},
ar:{title:'جدول دروس ركوب الخيل',back:'لوحة الإدارة',add:'درس جديد',edit:'تعديل الدرس',date:'التاريخ',time:'وقت البداية',instructor:'المدرب',arena:'الميدان',rider:'الفارس',horse:'الحصان',participants:'المشاركون',addParticipant:'إضافة مشارك',remove:'إزالة',choose:'اختر…',notes:'ملاحظات',saveButton:'حفظ الدرس',saving:'جارٍ الحفظ…',close:'إغلاق',cancelLesson:'إلغاء الدرس',complete:'تحديد كمكتمل',SCHEDULED:'مجدول',COMPLETED:'مكتمل',CANCELLED:'ملغى',today:'اليوم',previous:'اليوم السابق',next:'اليوم التالي',refresh:'تحديث',empty:'لا توجد دروس للعرض في اليوم المحدد.',duration:'مدة كل درس 30 دقيقة. يمكن إضافة عدة مشاركين إلى الدرس نفسه.',timezone:'المنطقة الزمنية',success:'تم حفظ الدرس بنجاح.',changed:'تم تحديث حالة الدرس.',invalid:'تحقق من الحقول. اختر مشاركاً واحداً على الأقل دون تكرار الفارس أو الحصان.',timeError:'الوقت غير صالح أو يتكرر عند تغيير التوقيت. اختر وقتاً آخر.',farm:'يجب إعداد مزرعة واحدة في النظام.',save:'تعذّر تحميل البيانات أو حفظها. حدّث الصفحة وتحقق من الاتصال.',disabled:'هذه العملية متاحة في وضع التطوير فقط.',inactive:'أحد الخيارات غير نشط أو لا ينتمي للمزرعة. حدّث الصفحة واختر بيانات نشطة.',conflict:'يوجد تعارض مع درس آخر للميدان أو المدرب أو أحد الفرسان أو الخيول. غيّر الوقت أو الاختيارات.',stale:'تم تغيير الدرس بعد فتح النموذج. أغلق النموذج وحدّث الصفحة ثم افتحه مجدداً.',future:'يمكن تحديد الدرس كمكتمل فقط بعد وقت انتهائه.',missing:'يجب توفر مدرب وفارس وحصان وميدان نشطين على الأقل لإضافة درس.',instructors:'إدارة المدربين',riders:'إدارة الفرسان',horses:'إدارة الخيول',inactiveLabel:'غير نشط',confirmCancel:'هل تريد إلغاء الدرس؟ سيبقى في السجل وسيصبح الوقت متاحاً.',confirmComplete:'هل تريد تحديد الدرس كمكتمل؟',all:'جميع الحالات',group:'جماعي',private:'فردي',max:'حتى 50 مشاركاً في الدرس.',history:'سجل التغييرات',historyEmpty:'لا توجد تغييرات موثقة بعد.',by:'بواسطة',system:'النظام',CREATED_AUDIT:'تم الإنشاء',UPDATED_AUDIT:'تم التحديث',CANCELLED_AUDIT:'تم الإلغاء',COMPLETED_AUDIT:'مكتمل'}
};
type Props={lessons:LessonView[];instructors:Choice[];riders:Choice[];horses:Choice[];arenas:ArenaChoice[];day:string;zone:string;issue?:'farm'|'save'};
type Participant={key:number;riderId:string;horseId:string};
export function LessonManager({lessons,instructors,riders,horses,arenas,day,zone,issue}:Props){
 const [lang,setLang]=useState<'he'|'ar'>('he'),[editing,setEditing]=useState<LessonView|null|undefined>(undefined),[participants,setParticipants]=useState<Participant[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState<LessonError|'success'|'changed'|null>(null),[filter,setFilter]=useState('all');
 const [pending,startTransition]=useTransition(),busyRef=useRef(false),serial=useRef(0),formRef=useRef<HTMLDivElement>(null),noticeRef=useRef<HTMLParagraphElement>(null);
 const router=useRouter(),t=words[lang],locked=busy||pending;
 const missing=!instructors.some(x=>x.isActive)||!riders.some(x=>x.isActive)||!horses.some(x=>x.isActive)||!arenas.some(x=>x.isActive);
 const field='mt-2 w-full min-w-0 rounded-xl border border-stone-300 bg-white px-3 py-3 text-base';
 const button='rounded-xl border border-stone-300 bg-white px-4 py-2 disabled:opacity-50';
 function navigate(date:string){if(!validDay(date))return;setMessage(null);startTransition(()=>router.push(`/lessons?date=${date}`,{scroll:false}));}
 function refresh(){startTransition(()=>router.refresh());}
 function open(lesson:LessonView|null){setEditing(lesson);setMessage(null);setParticipants(lesson?lesson.participants.map(p=>({key:++serial.current,riderId:String(p.riderId),horseId:String(p.horseId)})):[{key:++serial.current,riderId:'',horseId:''}]);setTimeout(()=>{formRef.current?.scrollIntoView({behavior:'smooth',block:'start'});formRef.current?.querySelector<HTMLInputElement>('input[name="day"]')?.focus({preventScroll:true});},0);}
 async function run(operation:()=>Promise<LessonResult>,saved:boolean){
 if(busyRef.current)return;busyRef.current=true;setBusy(true);setMessage(null);
 try{const result=await operation();if(result.ok){setEditing(undefined);setMessage(saved?'success':'changed');startTransition(()=>{if(result.day&&result.day!==day)router.push(`/lessons?date=${result.day}`,{scroll:false});router.refresh();});}else setMessage(result.error);}
 catch{setMessage('save');}finally{busyRef.current=false;setBusy(false);setTimeout(()=>noticeRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}),0);}}
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);void run(()=>saveLesson(data),true);}
 function status(lesson:LessonView,value:'CANCELLED'|'COMPLETED'){if(!window.confirm(value==='CANCELLED'?t.confirmCancel:t.confirmComplete))return;const form=new FormData();form.set('id',String(lesson.id));form.set('version',lesson.updatedAt);form.set('status',value);void run(()=>changeLessonStatus(form),false);}
 function options(choices:Choice[],used:string[]=[],current=''){return <><option value="">{t.choose}</option>{choices.filter(x=>x.isActive||String(x.id)===current).map(x=><option key={x.id} value={x.id} disabled={!x.isActive||(used.includes(String(x.id))&&current!==String(x.id))}>{x.name}{!x.isActive?` (${t.inactiveLabel})`:''}</option>)}</>;}
 function displayTime(iso:string){return new Intl.DateTimeFormat(lang==='he'?'he-IL':'ar',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
 function displayDateTime(iso:string){return new Intl.DateTimeFormat(lang==='he'?'he-IL':'ar',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
 const visible=lessons.filter(l=>filter==='all'||l.status===filter);
 return <main dir="rtl" lang={lang} className="min-h-screen bg-[#f5f3ee] px-4 py-8 text-[#243c32] sm:px-5"><div className="mx-auto max-w-6xl">
 <nav className="mb-8 flex flex-wrap items-center justify-between gap-4"><Link href="/admin" className="underline underline-offset-4">{t.back}</Link>{editing===undefined&&<Link href={`/lessons/week?date=${day}`} className="underline underline-offset-4">{lang==='he'?'יומן שבועי':'الجدول الأسبوعي'}</Link>}<button type="button" className={button} onClick={()=>setLang(lang==='he'?'ar':'he')} lang={lang==='he'?'ar':'he'}>{lang==='he'?'العربية':'עברית'}</button></nav>
 <header className="flex flex-wrap items-center justify-between gap-5 rounded-3xl bg-[#243c32] p-7 text-white"><div><h1 className="text-3xl font-bold">{t.title}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-white/80">{t.duration}</p><p className="mt-2 text-xs text-white/70">{t.timezone}: <bdi>{zone}</bdi></p></div><button type="button" disabled={!!issue||missing||locked||editing!==undefined} onClick={()=>open(null)} className="rounded-xl bg-[#d8bf8b] px-6 py-3 font-bold text-[#243c32] disabled:opacity-50">+ {t.add}</button></header>
 {issue&&<p role="alert" className="mt-5 rounded-xl bg-amber-100 p-5">{t[issue]} <button onClick={refresh} className="underline">{t.refresh}</button></p>}
 {!issue&&missing&&<aside className="mt-5 rounded-xl bg-amber-50 p-5"><p>{t.missing}</p><div className="mt-3 flex flex-wrap gap-4"><Link href="/instructors" className="underline">{t.instructors}</Link><Link href="/riders" className="underline">{t.riders}</Link><Link href="/horses" className="underline">{t.horses}</Link></div></aside>}
 {message&&<p ref={noticeRef} role={message==='success'||message==='changed'?'status':'alert'} className={`mt-5 rounded-xl p-5 ${message==='success'||message==='changed'?'bg-emerald-100':'bg-amber-100'}`}>{message==='time'?t.timeError:t[message]}</p>}
 {editing!==undefined&&<div ref={formRef} className="mt-6 scroll-mt-5 rounded-2xl border border-stone-200 bg-white p-5 sm:p-7"><h2 className="mb-5 text-xl font-bold">{editing?t.edit:t.add}</h2><form key={editing?.id??'new'} onSubmit={submit}>
 <input type="hidden" name="id" value={editing?.id??''}/><input type="hidden" name="version" value={editing?.updatedAt??''}/>
 <fieldset disabled={locked} className="grid min-w-0 gap-5 sm:grid-cols-2">
 <label>{t.date} *<input name="day" type="date" required min="2000-01-01" max="2100-12-30" defaultValue={editing?localStamp(new Date(editing.startsAt),zone).slice(0,10):day} className={field}/></label>
 <label>{t.time} *<input name="time" type="time" required step={60} defaultValue={editing?localStamp(new Date(editing.startsAt),zone).slice(11):'16:00'} className={field}/></label>
 <label>{t.instructor} *<select name="instructorId" required defaultValue={editing?.instructorId??''} className={field}>{options(instructors,[],String(editing?.instructorId??''))}</select></label>
 <label>{t.arena} *<select name="arenaId" required defaultValue={editing?.arenaId??''} className={field}><option value="">{t.choose}</option>{arenas.filter(a=>a.isActive||a.id===editing?.arenaId).map(a=><option key={a.id} value={a.id} disabled={!a.isActive}>{lang==='he'?a.nameHe:a.nameAr}{!a.isActive?` (${t.inactiveLabel})`:''}</option>)}</select></label>
 <div className="min-w-0 sm:col-span-2"><h3 className="font-bold">{t.participants} ({participants.length})</h3><div className="mt-3 space-y-3">{participants.map((p,i)=><div key={p.key} className="grid min-w-0 items-end gap-3 rounded-xl bg-stone-50 p-4 sm:grid-cols-[1fr_1fr_auto]">
 <label>{t.rider} {i+1} *<select name="riderId" required value={p.riderId} className={field} onChange={e=>setParticipants(rows=>rows.map(row=>row.key===p.key?{...row,riderId:e.target.value}:row))}>{options(riders,participants.map(row=>row.riderId),p.riderId)}</select></label>
 <label>{t.horse} *<select name="horseId" required value={p.horseId} className={field} onChange={e=>setParticipants(rows=>rows.map(row=>row.key===p.key?{...row,horseId:e.target.value}:row))}>{options(horses,participants.map(row=>row.horseId),p.horseId)}</select></label>
 <button type="button" disabled={participants.length===1} aria-label={`${t.remove} ${i+1}`} onClick={()=>setParticipants(rows=>rows.filter(row=>row.key!==p.key))} className={button}>{t.remove}</button></div>)}</div>
 <button type="button" disabled={participants.length>=50} onClick={()=>setParticipants(rows=>[...rows,{key:++serial.current,riderId:'',horseId:''}])} className={`${button} mt-3`}>+ {t.addParticipant}</button>{participants.length>=50&&<p className="mt-2 text-sm">{t.max}</p>}</div>
 <label className="sm:col-span-2">{t.notes}<textarea name="notes" rows={3} maxLength={2000} defaultValue={editing?.notes??''} className={field}/></label>
 <div className="flex flex-wrap gap-3 sm:col-span-2"><button type="submit" className="rounded-xl bg-[#243c32] px-6 py-3 text-white">{busy?t.saving:t.saveButton}</button><button type="button" className={button} onClick={()=>{setEditing(undefined);setMessage(null);}}>{t.close}</button></div>
 </fieldset></form></div>}
 {!issue&&<><div className="my-6 flex flex-wrap items-end gap-3">
 <label className="min-w-0">{t.date}<input type="date" min="2000-01-01" max="2100-12-30" value={day} disabled={locked||editing!==undefined} onChange={e=>navigate(e.target.value)} className={field}/></label>
 <button type="button" className={button} disabled={locked||editing!==undefined||day<='2000-01-01'} onClick={()=>navigate(moveDay(day,-1))}>{t.previous}</button><button type="button" className={button} disabled={locked||editing!==undefined} onClick={()=>navigate(localStamp(new Date(),zone).slice(0,10))}>{t.today}</button><button type="button" className={button} disabled={locked||editing!==undefined||day>='2100-12-30'} onClick={()=>navigate(moveDay(day,1))}>{t.next}</button><button type="button" className={button} disabled={locked} onClick={refresh}>{t.refresh}</button>
 <select aria-label={t.all} className={button} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t.all}</option>{(['SCHEDULED','COMPLETED','CANCELLED'] as const).map(s=><option key={s} value={s}>{t[s]}</option>)}</select></div>
 <section aria-label={t.title} aria-busy={locked} className="grid gap-4 md:grid-cols-2">{visible.map(lesson=><article key={lesson.id} className={`min-w-0 rounded-2xl border border-stone-200 bg-white p-6 ${lesson.status==='CANCELLED'?'opacity-70':''}`}>
 <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold"><bdi>{displayTime(lesson.startsAt)} – {displayTime(lesson.endsAt)}</bdi></h2><span className={`rounded-full px-3 py-1 text-sm ${lesson.status==='SCHEDULED'?'bg-amber-50':lesson.status==='COMPLETED'?'bg-emerald-50':'bg-stone-100'}`}>{t[lesson.status]}</span></div>
 {localStamp(new Date(lesson.startsAt),zone).slice(0,10)!==day&&<p className="mt-2 text-sm">{t.date}: <bdi>{localStamp(new Date(lesson.startsAt),zone).slice(0,10)}</bdi></p>}
 <p className="mt-4 break-words font-semibold">{t.instructor}: {lesson.instructorName}</p><p className="mt-2 break-words text-sm">{t.arena}: {lang==='he'?lesson.arenaHe:lesson.arenaAr}</p><p className="mt-4 text-xs text-stone-500">{lesson.participants.length>1?t.group:t.private} · {lesson.participants.length} {t.participants}</p>
 <ul className="mt-2 space-y-2">{lesson.participants.map(p=><li key={p.riderId} className="break-words rounded-lg bg-stone-50 px-3 py-2 text-sm">{p.riderName} · {t.horse}: {p.horseName}</li>)}</ul>{lesson.notes&&<p className="mt-4 whitespace-pre-wrap break-words text-sm text-stone-600">{lesson.notes}</p>}
 {lesson.status==='SCHEDULED'&&<div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={locked||editing!==undefined} onClick={()=>open(lesson)} className={button}>{t.edit}</button><button type="button" disabled={locked||editing!==undefined} onClick={()=>status(lesson,'COMPLETED')} className={button}>{t.complete}</button><button type="button" disabled={locked||editing!==undefined} onClick={()=>status(lesson,'CANCELLED')} className={`${button} text-red-700`}>{t.cancelLesson}</button></div>}
 <details className="mt-5 border-t border-stone-200 pt-4"><summary className="cursor-pointer font-semibold">{t.history} ({lesson.audits.length})</summary>{lesson.audits.length?<ol className="mt-3 space-y-3">{lesson.audits.map(a=><li key={a.id} className="rounded-xl bg-stone-50 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><b>{t[`${a.action}_AUDIT` as keyof typeof t]}</b><span className="text-xs text-stone-500"><bdi>{displayDateTime(a.createdAt)}</bdi></span></div><p className="mt-1 break-words">{lang==='he'?a.descriptionHe:a.descriptionAr}</p><p className="mt-1 text-xs text-stone-500">{t.by}: {a.actorName??t.system}</p></li>)}</ol>:<p className="mt-3 text-sm text-stone-500">{t.historyEmpty}</p>}</details></article>)}</section>{!visible.length&&<p className="rounded-2xl border border-dashed border-stone-300 p-10 text-center">{t.empty}</p>}</>}
 </div></main>;
}
