'use client';
import Link from 'next/link';
import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { localStamp, moveDay } from '@/lib/lesson-time';
import { lessonTouchesDay, weekDates } from '@/lib/lesson-week';
type Lesson={id:number;startsAt:string;endsAt:string;status:'SCHEDULED'|'COMPLETED'|'CANCELLED';instructorId:number;instructorName:string;arenaId:number;arenaHe:string;arenaAr:string;participants:{riderName:string;horseName:string}[]};
const words={
 he:{title:'יומן שבועי',intro:'כל השבוע — ראשון עד שבת',back:'לוח הניהול',daily:'יומן יומי',previous:'שבוע קודם',next:'שבוע הבא',current:'השבוע הנוכחי',date:'בחירת תאריך בשבוע',refresh:'רענון',instructors:'כל המדריכים',arenas:'כל המגרשים',statuses:'כל המצבים',active:'ללא שיעורים שבוטלו',SCHEDULED:'מתוכנן',COMPLETED:'הושלם',CANCELLED:'בוטל',empty:'אין שיעורים להצגה',open:'פתיחת היום / שיבוץ',today:'היום',count:'שיעורים לפי הסינון',riders:'שיבוצי משתתפים',hint:'לחץ על יום כדי להוסיף שיעור, או על שיעור כדי לפתוח את היומן היומי לעריכה. ניתן לגלול את השבוע אופקית.',farm:'נדרשת חווה אחת מוגדרת במערכת.',save:'לא הצלחנו לטעון את היומן. בדוק את החיבור ונסה לרענן.',horse:'סוס',instructor:'מדריך',arena:'מגרש',from:'התחיל בתאריך',reset:'איפוס סינון',zone:'אזור זמן'},
 ar:{title:'الجدول الأسبوعي',intro:'الأسبوع كاملاً — من الأحد إلى السبت',back:'لوحة الإدارة',daily:'الجدول اليومي',previous:'الأسبوع السابق',next:'الأسبوع التالي',current:'الأسبوع الحالي',date:'اختيار تاريخ ضمن الأسبوع',refresh:'تحديث',instructors:'جميع المدربين',arenas:'جميع الميادين',statuses:'جميع الحالات',active:'دون الدروس الملغاة',SCHEDULED:'مجدول',COMPLETED:'مكتمل',CANCELLED:'ملغى',empty:'لا توجد دروس للعرض',open:'فتح اليوم / إضافة درس',today:'اليوم',count:'دروس حسب التصفية',riders:'حجوزات المشاركين',hint:'اضغط على اليوم لإضافة درس، أو على الدرس لفتح الجدول اليومي وتعديله. يمكنك تمرير الأسبوع أفقياً.',farm:'يجب إعداد مزرعة واحدة في النظام.',save:'تعذّر تحميل الجدول. تحقق من الاتصال وحاول التحديث.',horse:'الحصان',instructor:'المدرب',arena:'الميدان',from:'بدأ بتاريخ',reset:'إعادة ضبط التصفية',zone:'المنطقة الزمنية'}
};
export function LessonWeek({lessons,days,today,zone,issue}:{lessons:Lesson[];days:string[];today:string;zone:string;issue?:'farm'|'save'}){
 const [lang,setLang]=useState<'he'|'ar'>('he'),[instructor,setInstructor]=useState('all'),[arena,setArena]=useState('all'),[status,setStatus]=useState('active'),[pending,startTransition]=useTransition();
 const router=useRouter(),t=words[lang],button='rounded-xl border border-stone-300 bg-white px-4 py-2 text-sm disabled:opacity-50';
 const instructorOptions=[...new Map(lessons.map(l=>[String(l.instructorId),l.instructorName])).entries()];
 const arenaOptions=[...new Map(lessons.map(l=>[String(l.arenaId),lang==='he'?l.arenaHe:l.arenaAr])).entries()];
 const filtered=lessons.filter(l=>(instructor==='all'||String(l.instructorId)===instructor)&&(arena==='all'||String(l.arenaId)===arena)&&(status==='all'||(status==='active'?l.status!=='CANCELLED':l.status===status)));
 function canGo(day:string){try{weekDates(day);return true;}catch{return false;}}
 function go(day:string){if(!canGo(day))return;startTransition(()=>router.push(`/lessons/week?date=${day}`,{scroll:false}));}
 function date(day:string,weekday=false){return new Intl.DateTimeFormat(lang==='he'?'he-IL':'ar',{timeZone:'UTC',day:'2-digit',month:'2-digit',...(weekday?{weekday:'long' as const}:{year:'numeric' as const})}).format(new Date(`${day}T12:00:00Z`));}
 function time(iso:string){return new Intl.DateTimeFormat(lang==='he'?'he-IL':'ar',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
 return <main dir="rtl" lang={lang} className="min-h-screen bg-[#f5f3ee] px-4 py-8 text-[#243c32] sm:px-6"><div className="mx-auto max-w-[1700px]">
  <nav className="mb-7 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-5"><Link href="/admin" className="underline underline-offset-4">{t.back}</Link><Link href={`/lessons?date=${days.includes(today)?today:days[0]}`} className="underline underline-offset-4">{t.daily}</Link></div><button type="button" className={button} lang={lang==='he'?'ar':'he'} onClick={()=>setLang(lang==='he'?'ar':'he')}>{lang==='he'?'العربية':'עברית'}</button></nav>
  <header className="rounded-3xl bg-[#243c32] p-7 text-white"><p className="text-sm text-[#d8bf8b]">{t.intro}</p><h1 className="mt-3 text-3xl font-bold">{t.title}</h1><p className="mt-3 text-lg"><bdi>{date(days[0])} – {date(days[6])}</bdi></p><p className="mt-3 text-xs text-white/70">{t.zone}: <bdi>{zone}</bdi></p></header>
  {issue?<p role="alert" className="mt-6 rounded-xl bg-amber-100 p-5">{t[issue]} <button type="button" onClick={()=>startTransition(()=>router.refresh())} className="underline">{t.refresh}</button></p>:<>
  <div className="my-5 flex flex-wrap items-end gap-3"><label className="text-sm">{t.date}<input type="date" min="2000-01-02" max="2100-12-25" value={days[0]} disabled={pending} onChange={e=>go(e.target.value)} className="mt-2 block min-w-0 rounded-xl border border-stone-300 bg-white px-4 py-2 text-base"/></label><button type="button" disabled={pending||!canGo(moveDay(days[0],-7))} onClick={()=>go(moveDay(days[0],-7))} className={button}>{t.previous}</button><button type="button" disabled={pending} onClick={()=>go(today)} className={button}>{t.current}</button><button type="button" disabled={pending||!canGo(moveDay(days[0],7))} onClick={()=>go(moveDay(days[0],7))} className={button}>{t.next}</button><button type="button" disabled={pending} onClick={()=>startTransition(()=>router.refresh())} className={button}>{t.refresh}</button></div>
  <div className="mb-5 flex flex-wrap gap-3"><select aria-label={t.instructors} value={instructor} onChange={e=>setInstructor(e.target.value)} className={button}><option value="all">{t.instructors}</option>{instructor!=='all'&&!instructorOptions.some(([id])=>id===instructor)&&<option value={instructor}>#{instructor}</option>}{instructorOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select aria-label={t.arenas} value={arena} onChange={e=>setArena(e.target.value)} className={button}><option value="all">{t.arenas}</option>{arena!=='all'&&!arenaOptions.some(([id])=>id===arena)&&<option value={arena}>#{arena}</option>}{arenaOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select aria-label={t.statuses} value={status} onChange={e=>setStatus(e.target.value)} className={button}><option value="active">{t.active}</option><option value="all">{t.statuses}</option>{(['SCHEDULED','COMPLETED','CANCELLED'] as const).map(s=><option key={s} value={s}>{t[s]}</option>)}</select><button type="button" className={button} onClick={()=>{setInstructor('all');setArena('all');setStatus('active');}}>{t.reset}</button></div>
  <div className="mb-4 flex flex-wrap gap-x-6 gap-y-2 text-sm"><p><strong>{filtered.length}</strong> {t.count}</p><p><strong>{filtered.reduce((sum,l)=>sum+l.participants.length,0)}</strong> {t.riders}</p></div><p className="mb-4 text-sm leading-7 text-stone-600">{t.hint}</p>
  <div tabIndex={0} role="region" aria-label={t.title} aria-busy={pending} className={`overflow-x-auto rounded-2xl border border-stone-200 focus-visible:outline-2 focus-visible:outline-[#243c32] ${pending?'opacity-60':''}`}><div className="grid min-w-[1470px] grid-cols-7 items-stretch bg-stone-200 gap-px">
   {days.map(day=><section key={day} aria-label={date(day,true)} className="min-w-0 bg-[#f9f8f4]">
    <header className={`min-h-36 border-b p-4 ${day===today?'border-[#d8bf8b] bg-[#f0e5cb]':'border-stone-200 bg-white'}`}><h2 className="text-base font-bold">{date(day,true)} {day===today&&<span className="ms-1 text-xs">● {t.today}</span>}</h2><Link href={`/lessons?date=${day}`} className="mt-3 inline-block text-sm underline underline-offset-4">{t.open}</Link></header>
    <div className="space-y-3 p-3">{filtered.filter(l=>lessonTouchesDay(l,day,zone)).map(l=><Link key={l.id} href={`/lessons?date=${day}`} className={`block rounded-xl border border-stone-200 bg-white p-3 shadow-sm transition hover:border-[#243c32] focus-visible:outline-2 ${l.status==='CANCELLED'?'opacity-60':''}`}>
     <p className="text-lg font-bold"><bdi>{time(l.startsAt)} – {time(l.endsAt)}</bdi></p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs ${l.status==='SCHEDULED'?'bg-amber-50':l.status==='COMPLETED'?'bg-emerald-50':'bg-stone-100'}`}>{t[l.status]}</span>
     {localStamp(new Date(l.startsAt),zone).slice(0,10)!==day&&<p className="mt-2 text-xs">{t.from}: {date(localStamp(new Date(l.startsAt),zone).slice(0,10))}</p>}
     <p className="mt-3 break-words text-sm font-semibold">{t.instructor}: {l.instructorName}</p><p className="mt-1 break-words text-xs text-stone-600">{t.arena}: {lang==='he'?l.arenaHe:l.arenaAr}</p>
     <ul className="mt-3 space-y-2 border-t border-stone-100 pt-3">{l.participants.map((p,i)=><li key={i} className="break-words text-xs leading-5">{p.riderName}<br/><span className="text-stone-500">{t.horse}: {p.horseName}</span></li>)}</ul>
    </Link>)}{!filtered.some(l=>lessonTouchesDay(l,day,zone))&&<p className="py-8 text-center text-sm text-stone-500">{t.empty}</p>}</div>
   </section>)}
  </div></div></>}
 </div></main>;
}
