'use client';
import { useActionState, useState } from 'react';
import Link from 'next/link';
import { createUser, toggleUser, type UserActionState } from '@/app/users/actions';
const initial:UserActionState={};
type Option={id:number;name:string};
type U={id:number;username:string;displayName:string;role:'ADMIN'|'INSTRUCTOR'|'RIDER';isActive:boolean;instructor?:{name:string}|null;rider?:{name:string}|null};
export function UserManager({users,instructors,riders}:{users:U[];instructors:Option[];riders:Option[]}){
 const [state,action,pending]=useActionState(createUser,initial);const [role,setRole]=useState<'ADMIN'|'INSTRUCTOR'|'RIDER'>('INSTRUCTOR');
 const errors={invalid:'יש למלא את כל הפרטים. הסיסמה חייבת להכיל לפחות 8 תווים.',exists:'שם המשתמש כבר קיים.',farm:'לא נמצאה חווה מתאימה.',link:'המדריך/הרוכב כבר מקושר לחשבון או אינו פעיל.',save:'שמירת המשתמש נכשלה.'};
 const options=role==='INSTRUCTOR'?instructors:role==='RIDER'?riders:[];
 return <main dir="rtl" className="min-h-screen bg-[#f5f3ee] px-5 py-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-[#9a7132]">ניהול הרשאות / إدارة الصلاحيات</p><h1 className="mt-2 text-3xl font-bold">משתמשים</h1></div><Link href="/admin" className="rounded-xl border border-stone-300 bg-white px-4 py-2">חזרה לניהול</Link></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><section className="rounded-3xl bg-white p-6"><h2 className="text-xl font-bold">יצירת חשבון</h2><form action={action} className="mt-5 space-y-4"><input name="displayName" required placeholder="שם מלא" className="w-full rounded-xl border border-stone-300 px-4 py-3"/><input name="username" required placeholder="שם משתמש באנגלית" className="w-full rounded-xl border border-stone-300 px-4 py-3"/><input name="password" type="password" minLength={8} required placeholder="סיסמה — לפחות 8 תווים" className="w-full rounded-xl border border-stone-300 px-4 py-3"/><select name="role" value={role} onChange={e=>setRole(e.target.value as typeof role)} className="w-full rounded-xl border border-stone-300 px-4 py-3"><option value="INSTRUCTOR">מדריך / مدرب</option><option value="RIDER">רוכב / فارس</option><option value="ADMIN">מנהל / مدير</option></select>{role!=='ADMIN'&&<select name="targetId" required className="w-full rounded-xl border border-stone-300 px-4 py-3"><option value="">{role==='INSTRUCTOR'?'בחר מדריך':'בחר רוכב'}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}{state.error&&<p className="rounded-xl bg-amber-50 p-3 text-sm">{errors[state.error]}</p>}{state.ok&&<p className="rounded-xl bg-emerald-50 p-3 text-sm">המשתמש נוצר בהצלחה.</p>}<button disabled={pending} className="w-full rounded-xl bg-[#243c32] px-5 py-3 font-bold text-white">{pending?'שומר…':'צור משתמש'}</button></form></section>
 <section className="rounded-3xl bg-white p-6"><h2 className="text-xl font-bold">חשבונות קיימים</h2><div className="mt-5 space-y-3">{users.map(u=><article key={u.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-stone-200 p-4"><div><p className="font-bold">{u.displayName}</p><p className="text-sm text-stone-600" dir="ltr">@{u.username}</p><p className="mt-1 text-sm">{u.role}{u.instructor?` · ${u.instructor.name}`:''}{u.rider?` · ${u.rider.name}`:''}</p></div><form action={toggleUser}><input type="hidden" name="id" value={u.id}/><button className={`rounded-xl px-4 py-2 text-sm ${u.isActive?'border border-stone-300':'bg-[#243c32] text-white'}`}>{u.isActive?'השבת':'הפעל'}</button></form></article>)}</div></section></div></div></main>;
}
